name: ant_time_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  domain:
    path: ./domain

  data:
    path: ./data

  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  google_fonts: ^4.0.3
  get_it: ^7.2.0
  bitsdojo_window: ^0.1.2
  flutter_svg: ^1.1.0
  url_launcher: ^6.1.3
  another_flushbar: ^1.10.29
  dropdown_button2: 1.9.4
  bloc_concurrency: ^0.2.0
  confetti: ^0.7.0
  window_manager: ^0.2.5
  dart_code_metrics: ^4.15.2
  flutter_markdown: ^0.6.10+2
  shared_preferences: ^2.0.15
  markdown: ^5.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  simple_animations: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/build_runner
  build_runner: ^2.1.11

  hive_generator: ^1.1.3

  flutter_lints: ^2.0.1

  flutter_launcher_icons: ^0.9.3
  msix: ^3.6.2

msix_config:
  display_name: Ant Time
  publisher_display_name: LTD Webant
  identity_name: com.webant.ant-time
  msix_version: 1.0.0.0
  logo_path: C:\path\to\logo.png
  capabilities: internetClient

flutter_icons:
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  generate: true

  fonts:
    - family: AntTime
      fonts:
      - asset: assets/icons/AntTime.ttf

  assets:
    - lib/localizations/l10n/app_ru.arb
    - lib/localizations/l10n/app_en.arb
    - assets/logo.svg
    - assets/icons/
    - assets/
