# Project Constants:
app_bundle_id: "com.webant.ant-time"

# Название проекта в апсентре
app_name: "ANTime-MacOS"

# Какая схема приложения будет использоваться для создания Beta и Release сборок приложения.
scheme: "Runner"

# AppleId под которым разрабатывается приложение. Необходимо для управления подписями и сертификатами.
apple_user: "a.korchevniy@bondsgirl.ru"
# Если один AppleID аккаунт состоит в нескольких командах, то необходимо указать id команды в котором идет разработка.
#team_id: "Q3N2U6LJD7"
team_id: ""
# Для управления сертификатами разработчика. Если приложение использует AppleId аккаунт заказчика,
# то ветка должна называться согласно названию приложению. Если приложение публикуется под нашим аккаунтом,
# тогда значение должно быть "vdaron@gmail.com"
#certificates_git_branch: "vdaron@gmail.com"
certificates_git_branch: ""

# В какую ветку будет залита версия после команды fastlane beta
beta_branch: "Beta"

# В какую ветку будет залита версия после команды fastlane release
release_branch: "AppStore"

# В какую команду тестирования будут отправляться сборки для тестирования.
webant_group: "WebAnt"

# В какую команду тестирования будут отправляться сборки для тестирования заказчиком.
customer_group: "WebAnt"

# Путь к файлу настройки проекта, чтобы туда устанавливать git версию репозитория.
plist_path: "ios/Runner/Info.plist"
