name: domain
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.4
  flutter:
    sdk: flutter
  retrofit: ^3.0.1+1

  data:
    path: ../data
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  build_runner: ^2.1.7
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: